# .azure-pipelines.yml
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    go version
    go get -v -t -d ./...
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gozure .
  displayName: 'Build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
- script: |
    echo "##vso[task.setvariable variable=artifact;isOutput=true]$(Build.ArtifactStagingDirectory)/gozure.zip"
  displayName: 'Set Artifact Variable'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
